### ISSUE TITLE
Push only on master

### ISSUE THREAD

**Issue by audig** [cnieg/samba-config-kube-pvc#4]
https://github.com/cnieg/samba-config-kube-pvc/blob/508491674db95495d3f9e3abfd5f505c1ff74900/.github/workflows/go.yml#L4

**Comment by arnou** [comment]
on en fait quoi de cette issue ?

**Comment by audig** [comment]
Je clos je ne me rappelle plus pourquoi j'avais créé celle ci.
J'ai moi même pas mis assez d'infos :(
